model:
  base_learning_rate: 1.0e-05
  target: zero123plus.model.MVDiffusion
  params:
    drop_cond_prob: 0.1

    # StableKeypoints configuration
    enable_stable_keypoints: true
    stable_keypoints_config:
      num_learnable_tokens: 16
      learning_rate: 1.0e-04  # Higher LR for learnable embeddings
      loss_weights:
        localization: 1.0
        equivariance: 0.1
        nvs: 1.0  # Maintain NVS training weight

    stable_diffusion_config:
      pretrained_model_name_or_path: sudo-ai/zero123plus-v1.2
      custom_pipeline: ./zero123plus

data:
  target: src.data.skeleton_objaverse.SkeletonDataModuleFromConfig
  params:
    batch_size: 1  # Reduced batch size due to additional skeleton processing
    num_workers: 2
    train:
      target: src.data.skeleton_objaverse.SkeletonObjaverseData
      params:
        root_dir: /objaverse/
        validation: false
    validation:
      target: src.data.skeleton_objaverse.SkeletonObjaverseData
      params:
        root_dir: /objaverse/
        validation: true


lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 1000 #1000 #50
      save_top_k: -1
      save_last: true
  callbacks: {}

  trainer:
    benchmark: true
    max_epochs: -1
    gradient_clip_val: 1.0
    val_check_interval: 1000 #1000 #50
    num_sanity_val_steps: 0
    accumulate_grad_batches: 6  # Accumulate gradients due to smaller batch size
    check_val_every_n_epoch: null
